name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  bloc: ^9.1.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  generators:
    git:
      url: https://github.com/NonymousMorlock/clean_architecture_code_generator.git
      path: generators
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
flutter:
  uses-material-design: true
