name: clean_arch_cli
description: A command-line interface for the Clean Architecture Code Generator
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  io: ^1.0.4
  path: ^1.8.3
  yaml: ^3.1.2
  mason_logger: ^0.2.11

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  clean_arch_cli:
