name: generators
description: Clean Architecture code generators for Dart/Flutter projects
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^9.0.0
  annotations:
    path: ../annotations/
  build: ^4.0.3
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  diff_match_patch: ^0.4.1
  equatable: ^2.0.5
  path: ^1.9.0
  source_gen: ^4.1.1
  yaml: ^3.1.2


dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  crypto: ^3.0.7
  glob: ^2.1.3
  mocktail: ^1.0.4
  package_config: ^2.2.0
  test: ^1.28.0
  very_good_analysis: ^10.0.0
