name: generators
description: Clean Architecture code generators for Dart/Flutter projects
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^6.0.0
  annotations:
    path: ../annotations/
  build: ^2.4.0
  code_builder: ^4.11.0
  dart_style: ^2.3.6
  equatable: ^2.0.5
  path: ^1.9.0
  source_gen: ^1.5.0
  yaml: ^3.1.2


dev_dependencies:
  build_runner: ^2.4.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
